config/routes.rb
Rails.application.routes.draw do
  root 'flights#index'

  get '/signup', to: "users#new"
  post '/signup', to: "users#create"

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  resources :users, only: [:show]
  resources :flights, only: [:index]
  resources :bookings, only: [:new, :create, :show]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :flight
  has_many :passengers

  accepts_nested_attributes_for :passengers, allow_destroy: true
end

app/models/city.rb
class City < ApplicationRecord
  has_many :arriving_flights, class_name: 'Flight', 
            foreign_key: 'destination_id', dependent: :destroy
  has_many :leaving_flights, class_name: 'Flight', 
            foreign_key: 'departure_id', dependent: :destroy
end

app/models/flight.rb
class Flight < ApplicationRecord
  belongs_to :destination, class_name: 'City'
  belongs_to :departure, class_name: 'City'
  has_many :bookings

  validates :destination, presence: true
  validates :departure, presence: true
  validates :take_off, presence: true

  def Flight.from_city city
    where('departure_id = ?', city)
  end
  
  def Flight.to_city city
    where('destination_id = ?', city)
  end

  def Flight.leaving date
    where('take_off > ? AND take_off < ?', date.to_datetime, date.next)
  end
end

app/models/passenger.rb
class Passenger < ApplicationRecord
  belongs_to :booking

  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, format: {with: VALID_EMAIL_REGEX}
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :name, presence: true
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, uniqueness: true, format: {with: VALID_EMAIL_REGEX}
  validates :password, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  include BookingsHelper

  def new
    flight = Flight.find(params[:booking][:flight])
    @number_of_passengers = params[:booking][:number_of_passengers]
    @booking = Booking.new(flight: flight)
  end

  def create
    @booking = Booking.new params_for_booking

    if @booking.save
      send_emails @booking
      flash[:succes] = 'Booked the flight'
      redirect_to @booking
    else
      @number_of_passengers = params[:booking][:number_of_passengers]
      render :new
    end
  end

  def show
    @booking = Booking.find(params[:id])
  end

  private

  def params_for_booking
    params.require(:booking).permit(:flight_id, passengers_attributes: [:name, :email])
  end

end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
    @cities = City.all
    @dates = Flight.select(:take_off).map {|flight| flight.take_off.to_date}.uniq

    if params[:flight].kind_of?(ActionController::Parameters)
      destination = params[:flight][:destination]
      departure = params[:flight][:departure]
      take_off = params[:flight][:take_off]
      @number_of_passengers = params[:flight][:number_of_passengers]
      @flights = Flight.from_city(departure).to_city(destination).leaving(take_off)
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  include SessionsHelper

  def new
  end

  def create
    user = User.find_by email: params[:session][:email]
    if user && user.authenticate(params[:session][:password])
      flash[:success] = "Correctly logged in"
      log_in user
      redirect_to user
    else
      flash.now[:errors] = "Invalid email or password"
      render :new
    end
  end

  def destroy
    logout
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include SessionsHelper

  before_action :check_user, only: [:show]

  def new
    @user = User.new
  end

  def create
    @user = User.new params_for_user
    if @user.save
      flash[:success] = "Correctly signed up"
      redirect_to @user
    else
      render :new
    end
  end

  def show
  end

  private
  def check_user
    @user = current_user
    unless @user == User.find_by(id: params[:id])
      flash[:allert] = "You do not have the permission to access this page"
      redirect_to login_path
    end
  end

  def params_for_user
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper

  def send_emails booking
    booking.passengers.each do |passenger|
      PassengerMailer.with(user: passenger, booking: booking).tickets_email.deliver_later
    end
  end
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in user
    session[:user_id] = user.id
  end

  def current_user
    current_user ||= User.find_by id: session[:user_id]
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    session.delete :user_id
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/bookings/new.html.erb
<h1>Booking your flight</h1>
<%= form_for @booking do |f| %>

  <%= render partial: 'shared/errors', locals: {errors: @booking.errors}%>

  <%= f.hidden_field :flight, value: @booking.flight.id%>
  <%= f.hidden_field :number_of_passengers, value: @number_of_passengers%>

  <%= f.label :flight_id, "Flight ID:" %>
  <%= f.text_field :flight_id, readonly: true %><br>

  <%@number_of_passengers.to_i.times do |i|%>
    <%= f.fields_for :passengers, @booking.passengers.build do |p_form|%>
      Passenger <%= i + 1%>: <br>

        <%if i == 0 && logged_in? %>
          <% user = current_user%>
        <%else%>
          <% user = User.new %>
        <%end%>

        <%= p_form.label :name %><br>
        <%= p_form.text_field :name, value: user.name %><br>

        <%= p_form.label :email %><br>
        <%= p_form.email_field :email, value: user.email %><br>
    <%end%>
  <%end%>

  <%= f.submit "Book your flight" %>
<%end%>

app/views/bookings/show.html.erb
<h1>Booking completed</h1>

<%= render partial: 'shared/booking', locals: {booking: @booking} %>

<strong> Passengers: </strong>
<ol>
  <% @booking.passengers.each do |passenger| %>
    <li><%= passenger.name%> - <%= passenger.email %></li>
  <%end%>
</ol>

app/views/flights/_flights_form.html.erb
<%= form_for(:booking, url: new_booking_path, method: :get) do |f|%>

  <%= f.hidden_field :number_of_passengers, value: @number_of_passengers%>

  <% flights.each do |flight| %>

    <%= f.radio_button :flight, flight.id %>

    <%= f.label 'flight_#{flight.id}'.to_sym, 
    "From: #{flight.departure.name},
    To: #{flight.destination.name}, 
    Leaving: #{flight.take_off}"%>
    <br>

  <%end%>

  <%= f.submit 'Book'%>
<%end%>

app/views/flights/_search_form.html.erb
<%= form_for(:flight, url: flights_path, method: :get) do |f| %>

  <%= f.label :departure, "From:" %><br>
  <%= f.collection_select(:departure, cities, :id, :name) %><br>

  <%= f.label :destination, "To:" %><br>
  <%= f.collection_select(:destination, cities, :id, :name) %><br>

  <%= f.label :number_of_passengers, "Number of passengers:" %><br>
  <%= f.collection_select(:number_of_passengers, (1..4), :itself, :itself)%><br>

  <%= f.label :take_off, "Date:"%><br>
  <%= f.collection_select(:take_off, dates, :itself, :itself) %><br>

  <%= f.submit "Search" %>
<%end%>

app/views/flights/index.html.erb
<h1>Book your flight</h1>

<div class= 'container'>
  <div class= 'search'>
    <%= render partial: 'search_form', locals: {cities: @cities, dates: @dates}%>
  </div>
</div>
<% if @flights %>
  <div class= 'container'>
    <div class= 'flights'>
      <%= render partial: 'flights_form', locals: {flights: @flights}%>
    </div>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<ul>
  <li><%= link_to "Home", root_path %></li>
  <% if logged_in?%>
    <li> <%= link_to "Profile", current_user %></li>
    <li> <%= link_to "Logout", logout_path, method: :delete %></li>
  <% else%>
    <li><%= link_to "Sign up", signup_path %></li>
    <li><%= link_to "Login", login_path %></li>
  <%end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FlightBooker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <header>
    <%= render partial: 'layouts/header'%>
  </header>
  <body>
  <% if flash.any? %>
    <ul>
    <% flash.each do |type, message| %>
      <li><%= message%></li>
    <%end%>
    </ul>
  <%end%>

    
    <%= yield %>
  </body>
</html>

app/views/shared/_booking.html.erb
<strong>From: </strong>
<%= booking.flight.departure.name %><br>

<strong>To: </strong>
<%= booking.flight.destination.name %><br>

<strong>Taking Off: </strong>
<%= booking.flight.take_off %><br>

app/views/shared/_errors.html.erb
<% if errors.any? %>
  <ul>
  <% errors.full_messages.each do |message|%>
    <li><%= message%></li>
  <%end%>
  </ul>
<%end%>

app/views/users/new.html.erb
<h1>Sign up!</h1>
<%= form_for(@user, url: signup_path) do |f|%>

  <%= render partial: 'shared/errors', locals: {errors: @user.errors} %>

  <%= f.label :name %><br>
  <%= f.text_field :name %><br>

  <%= f.label :email %><br>
  <%= f.email_field :email %><br>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br>

  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %><br>

  <%= f.submit "Sign up"%>
<%end%>

app/views/users/show.html.erb
<h1><%=@user.name%></h1>
<p>Flights</p>